// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Home$ReactTemplate = require("./Home.bs.js");

var MyAppStatus = /* module */[/* isUserLoggedIn */true];

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("Link");

function make(href, $staropt$star, children) {
  var className = $staropt$star !== undefined ? $staropt$star : "";
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReactDOMRe.createElementVariadic("a", {
                          className: className,
                          href: href,
                          onClick: Curry._1(self[/* handle */0], (function ($$event, _self) {
                                  $$event.preventDefault();
                                  return ReasonReact.Router[/* push */0](href);
                                }))
                        }, children);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var Link = /* module */[
  /* component */component,
  /* make */make
];

var component$1 = ReasonReact.reducerComponent("App");

function make$1(_children) {
  return /* record */[
          /* debugName */component$1[/* debugName */0],
          /* reactClassInternal */component$1[/* reactClassInternal */1],
          /* handedOffState */component$1[/* handedOffState */2],
          /* willReceiveProps */component$1[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var watcherID = ReasonReact.Router[/* watchUrl */2]((function (url) {
                      var match = url[/* path */0];
                      if (match) {
                        var exit = 0;
                        switch (match[0]) {
                          case "jokes" : 
                          case "login" : 
                              exit = 1;
                              break;
                          case "signup" : 
                              return Curry._1(self[/* send */3], /* ChangeRoute */[/* Jokes */3]);
                          default:
                            return Curry._1(self[/* send */3], /* ChangeRoute */[/* Jokes */3]);
                        }
                        if (exit === 1) {
                          return Curry._1(self[/* send */3], /* ChangeRoute */[/* Jokes */3]);
                        }
                        
                      } else {
                        return Curry._1(self[/* send */3], /* ChangeRoute */[/* Home */0]);
                      }
                    }));
              return Curry._1(self[/* onUnmount */4], (function (param) {
                            return ReasonReact.Router[/* unwatchUrl */3](watcherID);
                          }));
            }),
          /* didUpdate */component$1[/* didUpdate */5],
          /* willUnmount */component$1[/* willUnmount */6],
          /* willUpdate */component$1[/* willUpdate */7],
          /* shouldUpdate */component$1[/* shouldUpdate */8],
          /* render */(function (param) {
              var match = param[/* state */1][/* route */0];
              return React.createElement(React.Fragment, undefined, React.createElement("nav", undefined, ReasonReact.element(undefined, undefined, make("/jokes", undefined, /* array */["Jokes"]))), match !== 0 ? (
                            match >= 3 ? ReasonReact.element(undefined, undefined, Home$ReactTemplate.make("JOKES   !!!! Hellowjadjfas;djf", /* array */[])) : ReasonReact.element(undefined, undefined, Home$ReactTemplate.make("Hellowjadjfas;djf", /* array */[]))
                          ) : ReasonReact.element(undefined, undefined, Home$ReactTemplate.make("Hello, from App", /* array */[])));
            }),
          /* initialState */(function (param) {
              return /* record */[/* route : Home */0];
            }),
          /* retainedProps */component$1[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
            }),
          /* jsElementWrapped */component$1[/* jsElementWrapped */13]
        ];
}

exports.MyAppStatus = MyAppStatus;
exports.str = str;
exports.Link = Link;
exports.component = component$1;
exports.make = make$1;
/* component Not a pure module */
